image:
  file: .gitpod.Dockerfile

ports:
  # Laravel server
  - port: 80
    onOpen: open-preview
  # MySQL server
  - port: 3306
    onOpen: ignore

tasks:
  - init: >
      cp .env.example .env &&
      sed -i "s|APP_URL=|APP_URL=${GITPOD_WORKSPACE_URL}|g" .env &&
      sed -i "s|APP_URL=https://|APP_URL=https://80-|g" .env &&
      composer install &&
      npm i &&
      php artisan key:generate
    command: >
      ./vendor/bin/sail up
    
